version: '2'
services:
   nginx: 
        container_name: myngx
        image: nginx:1.10
        volumes: 
            - ./ng1.conf:/etc/nginx/conf.d/default.conf
            - ./ng_pub.crt:/etc/nginx/ssl/ng_pub.crt
            - ./ng_priv.key:/etc/nginx/ssl/ng_priv.key
            - ./static:/var/www/static
            - ./index.html:/var/www/html/index.html  
        ports:
            - 443:443


